#
# Module file for module 'vCheck-NSX'
#
# Generated by: Kevin Kirkpatrick
#
# Generated on: 3/16/2017
#

# set global: variable values
$global:vCheckPath   = $MyInvocation.MyCommand.Definition | Split-Path
$global:pluginXMLURL = "https://vcheck.report/plugins.xml"
$global:pluginURL    = "https://raw.github.com/alanrenouf/vCheck-{0}/master/Plugins/{1}/{2}"

# Import vCheck-Utils module into global scope
Import-Module -Name "$PSScriptRoot\Modules\vCheck-Utils.psm1" -Global

# Import global config file
$globalConfigFile = (Get-Item "$PSScriptRoot\Config\Global.Config.ps1").FullName

. $globalConfigFile

# Dot source Public & Private functions
$Public  = @( Get-ChildItem -Path $PSScriptRoot\Public\*.ps1 -ErrorAction SilentlyContinue )
$Private = @( Get-ChildItem -Path $PSScriptRoot\Private\*.ps1 -ErrorAction SilentlyContinue )

foreach ($import in @($Public + $Private)) {

    try {   # dot-source all functions

        . $import.FullName

    } catch {

        Write-Warning -Message "Could not load function { $($import.Name) }. $_"

    } # end t/c

} # end foreach

Set-Alias -Name 'Get-ID-String' -Value Get-IDString
Set-Alias -Name 'Get-ChartColours' -Value Get-ChartColors
Set-Alias -Name 'Schedule-vCheck' -Value Set-vCheckSchedule
Set-Alias -Name 'Upgrade-vCheckDirectory' -Value Update-vCheckDirectory